(()=>{
const COLORS={green:'#16a34a',yellow:'#eab308',red:'#dc2626'};
const LABEL={green:'VERIFIED',yellow:'CHECK',red:'ERROR'};
let audits=[];let activeStatus=null;
function statusOf(p){const s=String(p?.validationStatus||'yellow').trim().toLowerCase();return ['green','yellow','red'].includes(s)?s:'yellow';}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureStyles(){if(document.getElementById('validation-tracker-style'))return;const s=document.createElement('style');s.id='validation-tracker-style';s.textContent=`#validation-tracker{display:flex;gap:9px;align-items:center}.validation-counter{border:2px solid #cbd5e1;border-radius:999px;padding:9px 14px;background:#fff;font-size:14px;font-weight:900;line-height:1;cursor:pointer;box-shadow:0 2px 8px #0001;transition:transform .15s,box-shadow .15s}.validation-counter:hover,.validation-counter.is-active{transform:translateY(-1px);box-shadow:0 6px 14px #0002}.validation-counter.is-active{outline:3px solid #2563eb55}.validation-dot{width:13px;height:13px;border-radius:50%;display:inline-block;margin-right:6px;vertical-align:-1px}.validation-badge{position:absolute;top:8px;right:8px;z-index:5;border:0;border-radius:999px;color:#fff;padding:5px 8px;font-size:11px;font-weight:900;box-shadow:0 2px 8px #0002;cursor:pointer}.v2-test-info{position:relative;padding-right:30px}.v2-test-info .validation-badge{top:0;right:0;min-width:24px;height:24px;padding:0;border-radius:50%}.validation-pop{position:fixed;z-index:9999;max-width:340px;max-height:70vh;overflow:auto;background:#fff;color:#111827;border:1px solid #d1d5db;border-radius:12px;padding:14px;box-shadow:0 18px 45px #0004;font-size:13px}.validation-pop h4{font-weight:900;margin:0 0 8px}.validation-pop .vcheck{display:flex;justify-content:space-between;gap:16px;padding:3px 0}.validation-pop .vissue{margin-top:8px;padding-top:8px;border-top:1px solid #e5e7eb;color:#b45309}[data-theme=dark] .validation-pop{background:#111827;color:#f3f4f6;border-color:#374151}`;document.head.appendChild(s);}
function tracker(data){const host=document.getElementById('header-controls');if(!host)return;document.getElementById('validation-tracker')?.remove();const counts={green:0,yellow:0,red:0};data.forEach(p=>counts[statusOf(p)]++);const box=document.createElement('div');box.id='validation-tracker';box.title=`Catalog validation filters · ${data.length} perfumes`;const refresh=()=>box.querySelectorAll('.validation-counter').forEach(b=>b.classList.toggle('is-active',b.dataset.validationFilter===activeStatus));['green','yellow','red'].forEach(k=>{const b=document.createElement('button');b.className='validation-counter';b.dataset.validationFilter=k;b.innerHTML=`<span class="validation-dot" style="background:${COLORS[k]}"></span>${LABEL[k]} ${counts[k]}`;b.title=`Filter ${LABEL[k]}: ${counts[k]}`;b.addEventListener('click',()=>{if(!Array.isArray(allPerfumes)||typeof displayPerfumes!=='function')return;activeStatus=activeStatus===k?null:k;const list=activeStatus?allPerfumes.filter(item=>statusOf(item?.item||item)===activeStatus):getFilteredPerfumes();displayPerfumes(list);refresh();window.scrollTo({top:0,behavior:'smooth'});});box.appendChild(b)});host.prepend(box);refresh();console.info('Shobi QA tracker',counts,'total',data.length);}
function popup(p,anchor){document.querySelectorAll('.validation-pop').forEach(x=>x.remove());const d=document.createElement('div');d.className='validation-pop';const checks=p.validationChecks||{};const notes=p.validationNotesCount||0;const names={shobiProduct:'Shobi product page',shobiIdentity:'Shobi name + brand',identity:'Fragrantica identity',fid:'Fragrantica ID',url:'Direct URL / ID',socialCard:'Social Card of same ID',image:'Fragrantica image of same ID',notes:`Notes ${p.validationMatchedNotesCount||0}/${notes} in order`,icons:`Icons ${p.validationIconsCount||0}/${notes}`,gender:'Gender from Social Card',season:'Main Season from longest bar',originalProductType:'Wearable perfume original'};const st=statusOf(p);d.innerHTML=`<h4>${esc(p.code)} · ${LABEL[st]}</h4>`+Object.keys(names).map(k=>`<div class="vcheck"><span>${esc(names[k])}</span><b>${checks[k]?'✓':'✕'}</b></div>`).join('')+((p.validationIssues||[]).length?`<div class="vissue">${p.validationIssues.map(esc).join('<br>')}</div>`:'');document.body.appendChild(d);const r=anchor.getBoundingClientRect();d.style.left=Math.max(8,Math.min(innerWidth-d.offsetWidth-8,r.left))+'px';d.style.top=Math.min(innerHeight-d.offsetHeight-8,r.bottom+6)+'px';setTimeout(()=>document.addEventListener('click',e=>{if(!d.contains(e.target)&&e.target!==anchor)d.remove()},{once:true}),0);}
function findAudit(card){if(!card)return null;const code=card.dataset.validationCode||card.querySelector('[data-field="code"]')?.textContent.trim().toLowerCase();const matches=code?audits.filter(p=>String(p.code||'').trim().toLowerCase()===String(code).toLowerCase()):[];if(matches.length===1)return matches[0];const text=card.textContent.toLowerCase();return audits.find(p=>text.includes(String(p.brand||'').toLowerCase())&&text.includes(String(p.inspiredBy||'').toLowerCase()))||matches[0]||null;}
function decorate(){document.querySelectorAll('#resultsContainer > div').forEach(card=>{const p=findAudit(card);if(!p||card.querySelector('.validation-badge'))return;const st=statusOf(p);const b=document.createElement('button');b.className='validation-badge';b.style.background=COLORS[st];b.textContent=st==='green'?'✓':st==='red'?'✕':'!';b.title=`${LABEL[st]} · click for audit`;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();popup(p,b)});const rel=card.querySelector('.v2-test-info')||card.querySelector('.p-5.relative')||card;rel.appendChild(b);});}
Promise.all([
  fetch(`catalog_site.json?qa=${Date.now()}`,{cache:'no-store'}),
  fetch(`catalog-scope-exclusions.json?qa=${Date.now()}`,{cache:'no-store'})
]).then(async ([catalogResponse, scopeResponse])=>{
  if(!catalogResponse.ok)throw new Error(`catalog HTTP ${catalogResponse.status}`);
  const [catalog, scopeData]=await Promise.all([
    catalogResponse.json(),
    scopeResponse.ok ? scopeResponse.json() : Promise.resolve({codes:[]})
  ]);
  const excludedCodes=new Set(Array.isArray(scopeData?.codes)?scopeData.codes.map(code=>String(code||'').trim().toUpperCase()):[]);
  return catalog.filter(p=>!excludedCodes.has(String(p?.code||'').trim().toUpperCase()));
}).then(data=>{ensureStyles();audits=data;tracker(data);decorate();new MutationObserver(decorate).observe(document.getElementById('resultsContainer')||document.body,{childList:true,subtree:true});}).catch(console.error);
})();
