(()=>{
const COLORS={green:'#16a34a',yellow:'#eab308',red:'#dc2626'};
const LABEL={green:'VERIFIED',yellow:'CHECK',red:'ERROR'};
let audits=new Map();
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureStyles(){if(document.getElementById('validation-tracker-style'))return;const s=document.createElement('style');s.id='validation-tracker-style';s.textContent=`#validation-tracker{display:flex;gap:6px;align-items:center}.validation-counter{border:1px solid #d1d5db;border-radius:999px;padding:5px 8px;background:transparent;font-size:12px;font-weight:800;cursor:pointer}.validation-dot{width:10px;height:10px;border-radius:50%;display:inline-block;margin-right:4px}.validation-badge{position:absolute;top:8px;right:8px;z-index:5;border:0;border-radius:999px;color:#fff;padding:5px 8px;font-size:11px;font-weight:900;box-shadow:0 2px 8px #0002;cursor:pointer}.validation-pop{position:fixed;z-index:9999;max-width:340px;max-height:70vh;overflow:auto;background:#fff;color:#111827;border:1px solid #d1d5db;border-radius:12px;padding:14px;box-shadow:0 18px 45px #0004;font-size:13px}.validation-pop h4{font-weight:900;margin:0 0 8px}.validation-pop .vcheck{display:flex;justify-content:space-between;gap:16px;padding:3px 0}.validation-pop .vissue{margin-top:8px;padding-top:8px;border-top:1px solid #e5e7eb;color:#b45309}[data-theme=dark] .validation-pop{background:#111827;color:#f3f4f6;border-color:#374151}`;document.head.appendChild(s);}
function tracker(data){const host=document.querySelector('nav .flex.items-center.gap-3');if(!host||document.getElementById('validation-tracker'))return;const counts={green:0,yellow:0,red:0};data.forEach(p=>counts[p.validationStatus||'yellow']++);const box=document.createElement('div');box.id='validation-tracker';box.title='Catalog validation status';['green','yellow','red'].forEach(k=>{const b=document.createElement('button');b.className='validation-counter';b.dataset.validationFilter=k;b.innerHTML=`<span class="validation-dot" style="background:${COLORS[k]}"></span>${counts[k]}`;b.title=`${LABEL[k]}: ${counts[k]}`;box.appendChild(b)});host.prepend(box);}
function popup(p,anchor){document.querySelectorAll('.validation-pop').forEach(x=>x.remove());const d=document.createElement('div');d.className='validation-pop';const checks=p.validationChecks||{};const names={identity:'Identity',fid:'FID',url:'URL',socialCard:'Social Card',image:'Image',notes:`Notes ${p.validationNotesCount||0}`,icons:'Icons',gender:'Gender',season:'Season'};d.innerHTML=`<h4>${esc(p.code)} · ${LABEL[p.validationStatus||'yellow']}</h4>`+Object.keys(names).map(k=>`<div class="vcheck"><span>${esc(names[k])}</span><b>${checks[k]?'✓':'✕'}</b></div>`).join('')+((p.validationIssues||[]).length?`<div class="vissue">${p.validationIssues.map(esc).join('<br>')}</div>`:'');document.body.appendChild(d);const r=anchor.getBoundingClientRect();d.style.left=Math.max(8,Math.min(innerWidth-d.offsetWidth-8,r.left))+'px';d.style.top=Math.min(innerHeight-d.offsetHeight-8,r.bottom+6)+'px';setTimeout(()=>document.addEventListener('click',e=>{if(!d.contains(e.target)&&e.target!==anchor)d.remove()},{once:true}),0);}
function decorate(){document.querySelectorAll('[data-field="code"]').forEach(codeEl=>{const code=codeEl.textContent.trim();const p=audits.get(code);if(!p)return;const card=codeEl.closest('.bg-surface');if(!card||card.querySelector('.validation-badge'))return;const b=document.createElement('button');b.className='validation-badge';b.style.background=COLORS[p.validationStatus||'yellow'];b.textContent=(p.validationStatus||'yellow')==='green'?'✓':'!';b.title=`${LABEL[p.validationStatus||'yellow']} · click for audit`;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();popup(p,b)});const rel=card.querySelector('.p-5.relative')||card;rel.appendChild(b);});}
fetch('catalog_site.json').then(r=>r.json()).then(data=>{ensureStyles();audits=new Map(data.map(p=>[p.code,p]));tracker(data);decorate();new MutationObserver(decorate).observe(document.getElementById('resultsContainer')||document.body,{childList:true,subtree:true});}).catch(console.error);
})();
