# Additional Shobi-first mappings reviewed after the initial residual batch.
# code: (Fragrantica ID, brand, exact target name, rationale)
APPROVED_ADDITIONAL = {
    '118-HAM': ('27808', 'Hamidi Oud & Perfumes', 'Rehan', 'Shobi identifies REHAN - HAMIDI OUD; exact same-brand Fragrantica entry'),
    '172-SHALM': ('47982', 'Scent Salim', 'Moroccan Musk', 'Shobi identifies MOROCCAN MUSK - SCENT SALIM; exact same-brand Fragrantica entry'),
    '741-JUI': ('33567', 'Juicy Couture', 'Viva La Juicy Rose', 'Shobi residual is Viva La Juicy Rose; exact Juicy Couture 2015 entry'),
    '742-JUI': ('42053', 'Juicy Couture', 'Viva La Juicy Sucre', 'Shobi residual explicitly says VIVA LA JUICY SUCRE - COUTURE; exact 2016 entry'),
    '743-JUS': ('15287', 'Justin Bieber', 'Girlfriend', 'Shobi explicitly identifies GIRLFRIEND - JUSTIN BIEBER; exact 2012 entry'),
    '744-JUS': ('18665', 'Justin Bieber', 'The Key', 'Shobi explicitly identifies THE KEY - JUSTIN BIEBER; exact 2013 entry'),
    '745-KAR': ('24068', 'Karl Lagerfeld', 'Karl Lagerfeld for Her', 'Shobi residual explicitly specifies Karl Lagerfeld for Her Eau de Parfum; exact 2014 women EDP'),
    '746-KAR': ('35570', 'Karl Lagerfeld', 'Ocean View for Women', 'Shobi explicitly identifies OCEAN VIEW - KARL LAGERFELD in women category; exact 2016 women entry'),
    '770-LAP': ('824', 'La Prairie', 'Midnight Rain', 'Shobi explicitly identifies MIDNIGHT RAIN - LA PRAIRIE; base 2006 entry'),
    '771-LAP': ('823', 'La Prairie', 'Silver Rain', 'Shobi explicitly identifies SILVER RAIN - LA PRAIRIE and gives original 2004 notes; not Sheer/Shimmer flankers'),
    '772-LAD': ('15338', 'Lady Gaga', 'Fame', 'Shobi residual Fame plus orchid/jasmine/honey/apricot notes identifies Lady Gaga Fame 2012'),
    '825-MIC': ('39459', 'Michael Kors', 'Wonderlust', 'Shobi explicitly identifies WONDERLUST - MICHAEL KORS; base 2016 entry'),
    '827-MISN': ('33017', 'Missoni', 'Missoni (2015)', 'Shobi describes the modern fruity-floral Missoni; identity fits the 2015 Quentin Bisch release, not the 1981/2006 versions'),
    '840-NAO': ('905', 'Naomi Campbell', 'Naomi Campbell', 'Shobi residual is self-titled Naomi Campbell; exact 1999 debut entry'),
    '850-NIN': ('1014', 'Nina Ricci', "L'Air du Temps", 'Shobi explicitly identifies L AIR DU TEMPS; classic 1948 entry'),
    '851-NIN': ('29668', 'Nina Ricci', "L'Extase", 'Shobi explicitly identifies L EXTASE; base 2015 entry'),
    '852-NIN': ('39376', 'Nina Ricci', 'Luna', 'Shobi explicitly identifies LUNA; base 2016 entry'),
    '853-NIN': ('147', 'Nina Ricci', 'Nina', 'Current Shobi code 853-NIN explicitly identifies NINA; base 2006 apple fragrance'),
    '854-NIN': ('56162', 'Nina Ricci', 'Nina Rouge', 'Shobi code 854-NIN explicitly identifies NINA ROUGE and matching raspberry/citron/gardenia/ginger/caramel/vanilla notes'),
    '855-NIN': ('520', 'Nina Ricci', 'Premier Jour', 'Shobi explicitly identifies PREMIER JOUR; base 2001 entry'),
    '856-NIN': ('6382', 'Nina Ricci', 'Ricci Ricci', 'Shobi explicitly identifies RICCI RICCI; base 2009 entry'),
    '860-ORT': ('14909', 'Olfactive Studio', 'Lumiere Blanche', 'Shobi residual identifies Lumiere Blanche by Olfactive Studio; exact 2012 entry'),
    '861-OSC': ('43028', 'Oscar de la Renta', 'Rose', 'Shobi residual identifies Rose by Oscar de la Renta; exact 2016 entry'),
    '862-PAL': ('6044', 'Paloma Picasso', 'Mon Parfum', 'Shobi residual identifies Mon Parfum by Paloma Picasso; exact 1985 entry'),
    '868-PEN': ('38351', "Penhaligon's", 'Luna', 'Shobi residual identifies Luna by Penhaligons; exact 2016 perfume, not 2026 body mist'),
    '869-PIER': ('22817', 'Balmain Beauty', 'Extatic', 'Shobi residual identifies Extatic / Pierre Balmain; base 2014 EDP, not EDT flanker'),
    '875-PRSC': ('1055', 'Salvatore Ferragamo', 'Incanto Shine', 'Shobi residual identifies Incanto Shine by Salvatore Ferragamo; exact 2007 entry'),
    '880-PRSC': ('21977', 'Salvatore Ferragamo', 'Signorina Eleganza', 'Shobi residual identifies Signorina Eleganza; exact 2014 entry'),
    '884-RAL': ('14446', 'Ralph Lauren', 'Big Pony 2 for Women', 'Shobi residual is Big Pony 2 in women catalog; exact 2012 women entry, not 2010 men version'),
    '888-RCAV': ('41717', 'Roberto Cavalli', 'Divine Oud', 'Shobi residual identifies Divine Oud by Roberto Cavalli; exact 2016 entry'),
    '890-RCAV': ('17310', 'Roberto Cavalli', 'Roberto Cavalli Acqua', 'Shobi residual identifies Roberto Cavalli Acqua; exact 2013 women EDT'),
    '891-RCAV': ('18833', 'Roberto Cavalli', 'Roberto Cavalli Nero Assoluto', 'Shobi residual identifies Nero Assoluto; base 2013 entry, not Exclusive Edition'),
    '895-RCAV': ('837', 'Roberto Cavalli', 'Serpentine', 'Shobi residual identifies Serpentine; original 2005 entry'),
    '896-RCAV': ('22194', 'Roberto Cavalli', 'Tiger Oud', 'Shobi residual identifies Tiger Oud; exact Roberto Cavalli 2013 entry'),
    '897-RCAV': ('22194', 'Roberto Cavalli', 'Tiger Oud', 'Duplicate Shobi code variant for the same Tiger Oud identity; same exact Fragrantica target'),
    '900-ROG': ('17583', 'Roger & Gallet', 'Fleur de Figuier', 'Shobi residual says Fleur de Figuier without Eau de Parfum qualifier; maps to original 2013 EDT, not 2015 EDP'),
    '901-ROG': ('3482', 'Roger & Gallet', 'Rose', 'Shobi residual identifies Rose by Roger & Gallet; exact 2007 EDT entry'),
    '1186-JOO': ('43425', 'Joop!', 'WOW!', 'Previously reviewed exact same-brand target retained; Shobi residual identity is WOW by Joop'),
    '1188-JPG': ('39583', 'Jean Paul Gaultier', 'Le Male Essence de Parfum', 'Previously reviewed exact Shobi identity retained'),
    '1195-LAC': ('16456', 'Lacoste', 'Eau de Lacoste L.12.12 Rouge', 'Previously reviewed exact Shobi identity retained'),
    '1214-MON': ('45692', 'Montblanc', 'Legend Night', 'Previously reviewed exact Shobi identity retained'),
    '1217-MON': ('30991', 'Montblanc', 'Starwalker Extreme', 'Previously reviewed exact Shobi identity retained'),
    '1220-MOS': ('55858', 'Moschino', 'Toy Boy', 'Previously reviewed exact Shobi identity retained'),
    '1232-PR': ('526', 'Paco Rabanne', 'Paco Rabanne Pour Homme', 'Previously reviewed exact Shobi identity retained'),
    '1235-PR': ('515', 'Paco Rabanne', 'XS', 'Previously reviewed exact Shobi identity retained'),
    '1238-PAL': ('764', 'Paloma Picasso', 'Minotaure', 'Previously reviewed exact Shobi identity retained'),
    '1246-PRA': ('48682', 'Prada', 'Luna Rossa Black', 'Previously reviewed exact Shobi identity retained'),
    '1248-RAL': ('48482', 'Ralph Lauren', 'Polo Ultra Blue', 'Previously reviewed exact Shobi identity retained'),
    '1255-FER': ('1546', 'Ferrari', 'Scuderia Ferrari Black', 'Previously reviewed exact Shobi identity retained'),
    '1257-SER': ('2764', 'Serge Lutens', "Five O'Clock Au Gingembre", 'Previously reviewed exact Shobi identity retained'),
    '1258-SFER': ('26777', 'Salvatore Ferragamo', 'White Mimosa', 'Previously reviewed exact Shobi identity retained'),
    '1262-PR': ('48704', 'Paco Rabanne', 'Invictus Aqua 2018', 'Previously reviewed exact Shobi identity retained'),
    '2028-ZARK': ('54529', 'ZARKOPERFUME', 'Cloud Collection No. 3', 'Previously reviewed exact Shobi identity retained'),
}
