#!/usr/bin/env python3

NO_FORCE_EXTRA = {
    '228-DIP': ('Diptyque', 'Feuille de Lavande', 'candle/home scent identity; do not substitute Eau de Lavande perfume'),
    '230-DIP': ('Diptyque', 'Opopanax', 'room spray/home fragrance identity; do not substitute a Diptyque perfume'),
    '258-JOM': ('Jo Malone London', 'Green Tomato Leaf', 'current Jo Malone identity is hand wash/home scent, not a perfume target'),
    '261-JOM': ('Jo Malone London', 'Incense & Embers', 'home candle/home fragrance identity; do not substitute Incense & Cedrat'),
    '289-JOM': ('Jo Malone London', 'Sweet Almond & Macaroon', 'official Jo Malone product is a scented candle/home fragrance, not a perfume target'),
    '311-MOL': ('Molton Brown', 'Amber Cocoon', 'body/home product identity; no safe exact Fragrantica perfume target'),
    '313-MOL': ('Molton Brown', 'Thai Vert', 'Molton Brown trade name exists across class-3/home-related goods but no safe exact Fragrantica perfume page was found; do not guess'),
    '314-MOL': ('Molton Brown', 'Ziao Jao', 'Shobi identifies ZIAO JAO - MOLTON BROWN; no safe exact Fragrantica perfume target found'),
    '326-PECK': ("Pecksniff's", 'Calm', 'Pecksniff Mood Therapy Calm is documented as a body/guest collection scent; no safe exact Fragrantica perfume target found'),
    '330-PG': ('P&G', 'Oriental Blossom', 'Shobi labels P&G Oriental Blossom, while web evidence points to household/laundry fragrance naming rather than a safe perfume identity; do not cross-brand or guess'),
    '331-PG': ('P&G', 'Crystal Water & Water Lily', 'Shobi labels P&G Crystal Water & Water Lily; no safe Fragrantica perfume identity found and this appears to be a consumer-product scent rather than a standalone perfume'),
    '334-SHI': ('Shirley May', 'Shirley May', 'Shobi explicitly names SHIRLEY MAY - SHIRLEY MAY, but Fragrantica lists the Shirley May brand catalog without a safe exact self-titled target; do not guess another Shirley May fragrance'),
    '335-THCO': ('The White Company', 'Cashmere Blanc', 'Shobi identifies CASHMERE BLANC - THE WHITE COMPANY; no safe exact Fragrantica perfume target found, and The White Company fragrance range is primarily home scent/body products'),
    '336-THCO': ('The White Company', 'Narcissus Noir', 'Shobi identifies NARCISSUS NOIR - THE WHITE COMPANY; no safe exact Fragrantica perfume target found, and The White Company fragrance range is primarily home scent/body products'),
    '379-YAN': ('Yankee Candle', 'Clean Cotton', 'candle/home fragrance identity'),
    '380-YAN': ('Yankee Candle', 'Fall Festival', 'candle/home fragrance identity'),
    '381-YAN': ('Yankee Candle', 'Fresh Cut Roses', 'candle/home fragrance identity'),
    '382-YAN': ('Yankee Candle', 'Pomegranate Cider', 'candle/home fragrance identity'),
    '383-YAN': ('Yankee Candle', 'Wedding Day', 'candle/home fragrance identity'),
    '564-DOL': ('Dolce & Gabbana', 'Sexy Chocolate', 'no authentic Dolce & Gabbana fragrance by this name; do not force a false target'),
    '570-DOL': ('Dolce & Gabbana', 'Red Cup', 'residual label is only RED CUP under Dolce & Gabbana suffix with no recoverable exact perfume identity; do not guess'),
    '904-SALV': ('Salvador Dali', 'Salvador Dali fragrances', 'generic brand/catalog label rather than a unique perfume identity; no exact target can be selected safely'),
    '1526-AL HAR': ('Al Haramain Perfumes', 'Mukhallat Al Emirates', 'real Al Haramain attar is referenced on Fragrantica community pages, but no safe exact encyclopedia page/ID was found; do not substitute another Mukhallath'),
    '1550-YAN': ('Yankee Candle', 'Home Sweet Home', 'candle/home fragrance identity'),
    '1748-BYR': ('Byredo', 'Marijuana', 'no safe authentic Byredo perfume target'),
    '1955-LAP': ('La Prairie', 'Cellular Energizing', 'body spray/body product rather than standard perfume identity'),
    '2085-CLIV': ('Clive Christian', 'X Neroli Limited Edition', 'real product identity but no safe Fragrantica page target found'),
    '2178-MON': ('Unknown MON brand', 'Pour Homme', 'label is generic and MON suffix is ambiguous across existing catalog brands; no safe exact identity without stronger Shobi metadata'),
    '2552-SOR': ('Unknown SOR brand', 'Night Horse', 'Fragrantica has a Night Horse by Siordia Parfums, but Shobi brand identity is not established strongly enough to cross-brand; do not force'),
    '2586-DIP': ('Diptyque', 'Biscuit', 'Diptyque Biscuit is a home/candle identity rather than a safe standalone perfume target'),
    '2701-DIP': ('Diptyque', 'Cafe Verlet', 'Diptyque Cafe/Café Verlet is a candle/home fragrance identity; no safe perfume target'),
    '2816-MOOD': ('Mood London', 'Blonde Maracuja', 'no safe exact Fragrantica encyclopedia target found for the Shobi identity; do not substitute Oud Maracuja or a different brand'),
}
