# Additional Shobi-first mappings reviewed after the initial residual batch.
# code: (Fragrantica ID, brand, exact target name, rationale)
APPROVED_ADDITIONAL = {
    '118-HAM': ('27808', 'Hamidi Oud & Perfumes', 'Rehan', 'Shobi identifies REHAN - HAMIDI OUD; exact same-brand Fragrantica entry'),
    '172-SHALM': ('47982', 'Scent Salim', 'Moroccan Musk', 'Shobi identifies MOROCCAN MUSK - SCENT SALIM; exact same-brand Fragrantica entry'),
    '741-JUI': ('33567', 'Juicy Couture', 'Viva La Juicy Rose', 'Shobi residual is Viva La Juicy Rose; exact Juicy Couture 2015 entry'),
    '742-JUI': ('42053', 'Juicy Couture', 'Viva La Juicy Sucre', 'Shobi residual explicitly says VIVA LA JUICY SUCRE - COUTURE; exact 2016 entry'),
    '743-JUS': ('15287', 'Justin Bieber', 'Girlfriend', 'Shobi explicitly identifies GIRLFRIEND - JUSTIN BIEBER; exact 2012 entry'),
    '744-JUS': ('18665', 'Justin Bieber', 'The Key', 'Shobi explicitly identifies THE KEY - JUSTIN BIEBER; exact 2013 entry'),
    '745-KAR': ('24068', 'Karl Lagerfeld', 'Karl Lagerfeld for Her', 'Shobi residual explicitly specifies Karl Lagerfeld for Her Eau de Parfum; exact 2014 women EDP'),
    '746-KAR': ('35570', 'Karl Lagerfeld', 'Ocean View for Women', 'Shobi explicitly identifies OCEAN VIEW - KARL LAGERFELD in women category; exact 2016 women entry'),
    '770-LAP': ('824', 'La Prairie', 'Midnight Rain', 'Shobi explicitly identifies MIDNIGHT RAIN - LA PRAIRIE; base 2006 entry'),
    '771-LAP': ('823', 'La Prairie', 'Silver Rain', 'Shobi explicitly identifies SILVER RAIN - LA PRAIRIE and gives original 2004 notes; not Sheer/Shimmer flankers'),
    '772-LAD': ('15338', 'Lady Gaga', 'Fame', 'Shobi residual Fame plus orchid/jasmine/honey/apricot notes identifies Lady Gaga Fame 2012'),
    '825-MIC': ('39459', 'Michael Kors', 'Wonderlust', 'Shobi explicitly identifies WONDERLUST - MICHAEL KORS; base 2016 entry'),
    '827-MISN': ('33017', 'Missoni', 'Missoni (2015)', 'Shobi describes the modern fruity-floral Missoni; identity fits the 2015 Quentin Bisch release, not the 1981/2006 versions'),
    '840-NAO': ('905', 'Naomi Campbell', 'Naomi Campbell', 'Shobi residual is self-titled Naomi Campbell; exact 1999 debut entry'),
    '850-NIN': ('1014', 'Nina Ricci', "L'Air du Temps", 'Shobi explicitly identifies L AIR DU TEMPS; classic 1948 entry'),
    '851-NIN': ('29668', 'Nina Ricci', "L'Extase", 'Shobi explicitly identifies L EXTASE; base 2015 entry'),
    '852-NIN': ('39376', 'Nina Ricci', 'Luna', 'Shobi explicitly identifies LUNA; base 2016 entry'),
    '853-NIN': ('147', 'Nina Ricci', 'Nina', 'Current Shobi code 853-NIN explicitly identifies NINA; base 2006 apple fragrance'),
    '854-NIN': ('56162', 'Nina Ricci', 'Nina Rouge', 'Shobi code 854-NIN explicitly identifies NINA ROUGE and matching raspberry/citron/gardenia/ginger/caramel/vanilla notes'),
    '855-NIN': ('520', 'Nina Ricci', 'Premier Jour', 'Shobi explicitly identifies PREMIER JOUR; base 2001 entry'),
    '856-NIN': ('6382', 'Nina Ricci', 'Ricci Ricci', 'Shobi explicitly identifies RICCI RICCI; base 2009 entry'),
}
